### ISSUE TITLE
[Request] Usernames not showing up

### ISSUE THREAD

**Issue by pain4gabriel** [CyR1en/Minecordbot#107]
### What is supposed to happen?
*Describe how you expected it to output or perform*:My bot prints out "Hearts" instead of the usernames, and a number, example: ❤️ 17:messahe

### What actually happens?
*Describe how the plugin behaves in this instance.*:Nothing happens special, but the usernames are glitched.

### What steps reproduce the problem?
1.n/a
2.n/a
3.n/a

------
### What is your Minecordbot version?
*Do not say latest. Please provide either a version or git commit number.*
 im sorry, i don't know. Latest as of 7th of January. Really sorry!

### What is your craftbukkit / spigot version?
*We do not provide support for forks of Spigot (Taco, Paper), Glowstone, or Sponge. If you have an issue with a fork, please test it with either Spigot or Craftbukkit before reporting your issue.*
 I don't know that either. It's forge.

### Please provide a link to the following:
*Please use Hastebin or GitHub Gists for these files.*
* Server Log - [Hastebin](http://hastebin.example.com)
* MCB Diagnostics Report - [Gist](http://gist.github.example.com)
* MCB Configuration File - [SomePasteSite](http://paste.example.com)
* Some other relevant config file - http://relevant.example.com
I can't provide these, i don't own the server
#### Screenshots / Video (*Optional*)
*Only relevant screenshots and videos, please.*

![Screenshot1](https://somthing.com/screen.png "Screen Shot 1")

**Comment by TheIntelloBox** [comment]
Hello,

The project is discontinued (and it has been for many years now).
We recommend checking out plugins like DiscordSRV, etc.

Moreover, we need the config.yml & chat.yml files to help you.

Best regards,
TheIntelloBox.
