### ISSUE TITLE
Is this for BungeeCord or Waterfall?

### ISSUE THREAD

**Issue by iGreenDogs** [CyR1en/Minecordbot#108]
Hello. I want to know if this MinecordBot is available for Bungee because I have a server with my friends, and I am always adding new bots and deleting servers. If not, its fine, Ill try  and find another plungin like this, if yes, great. It will be added to my server the second I see a reply saying that it is. Thanks :smile: :octocat:

**Comment by TheIntelloBox** [comment]
Hello,

Unfortunately, MinecordBot only supports Bukkit-based Minecraft servers (CraftBukkit, Spigot, etc). :D 

Best regards,
TheIntelloBox.

**Comment by CyR1en** [comment]
MinecordBot is indeed using Bukkit API. However, if setup in a specific way (where you put minecordbot in all of the proxies and use one bot), you can potentially achieve what you're trying to do. Disclaimer though, I have not tested this.
