### ISSUE TITLE
invite

### ISSUE THREAD

**Issue by DoctorCheese1** [CyR1en/MineCordBot#110]
this isnt a bot issue but all of your discord links are not working, but i need help with the bot. it would be easier to chat on discord

**Comment by DoctorCheese1** [comment]
what jdk version do i need to run build.bat

**Comment by CyR1en** [comment]
I no longer have a Discord server and Minecordbot have been abandoned for awhile now. But this was written with JDK 8 (knowns as 1.8), therefore the gradle VM should also be in 1.8.
