### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by ghost** [CyR1en/Minecordbot#21]
https://pastebin.com/4s3Km5wL

**Comment by ghost** [comment]
Now gives another crash: [16:05:44 ERROR]: [MineCordBot] Plugin MineCordBot v2.0.5 has failed to register events for class us.cyrien.minecordbot.listener.TabCompleteV2 because org/bukkit/event/server/TabCompleteEvent does not exist.

**Comment by TheFlagCourier** [comment]
Note: Spigot 1.8.8 - MCB Version 2.0.5
