### ISSUE TITLE
Reload does not fully support the Help Command when changing languages

### ISSUE THREAD

**Issue by TheFlagCourier** [CyR1en/Minecordbot#27]
![This occurs...](https://user-images.githubusercontent.com/2712890/27510595-ef1ded3a-58d9-11e7-805b-6fdd803311d9.png)
\- Source: @XxMoNsTeR 

Changing Localization requires users to restart their Minecraft Server for changes to fully take effect.

**Comment by CyR1en** [comment]
It's not a bug. Hot-Swap of Localization have not been implemented yet. I'll implemet this on the next update. I will also be doing a command for this! Hypie.

**Comment by CyR1en** [comment]
For now you can do /reload MineCordBot. Since mcb now supports /reload.
