### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by ViK0s** [CyR1en/Minecordbot#28]
Hi there, i have a problem with setting up the plugin, some error pops up when i lunch the server.         
Here is the error message: http://scr.hu/0w0vp/f90e2
I think it's probably something wrong with configuration i did so here is the screenshot of my config:
http://scr.hu/0w0vp/49fzj

I would be thankful if someone could help me.

**Comment by TheFlagCourier** [comment]
@ShadowGamer225 - Can you share with us the log file? I don't recall MineCordBot depending (or even using) Snakeyml - and the config screenshot doesn't appear to be what's causing the issue. I suspect we'll have to go deeper.

Also:
- What version of Java are you using?
- What version, or build, of MineCordBot are you using?

**Comment by TheFlagCourier** [comment]
I did notice that you are missusing blocked_command_prefix, but I doubt that's related.

Should be for blocking certain user messages from broadcasting, not commands.
(ie: If you have a music bot that uses % before it's commands, you would add "%" to this list.)

**Comment by CyR1en** [comment]
It's a problem with your polish localization file(pl.yml). 

Here's a possible fix.

1. Go to your plugins folder.
2. Open the resource folder for MineCordBot.
3. Open Localization folder.
4. Edit pl.yml with notepad++ or any advance text editor.
5. Go under mcb>commands>setgame>description(line: 67).
6. Make sure that the number of leading white spaces in front of description are six spaces. (Do not use tab)
7. Save and try to restart.

If problem persists. Please use a different localization while we try our best to resolve the problem.

**Comment by ViK0s** [comment]
@TheFlagCourier What do you mean by log file? Do i need to scroll the console and find MCB related lines? 
I'm using Java Version 8 Update 131 (build 1.8.0_131-b11)
I'm using the latest build of MCB.



@CyR1en Thanks for the possible fix but everything is alright with the 67 line.

**Comment by TheFlagCourier** [comment]
@ShadowGamer225 I meant the actual log file, as shown in the attachment. Though a screenshot also works if it provides enough information. You're free to censor user interaction where you see fit.

If you want to read your logs, use 7-zip to extract the .GZ files. I recommend you use [GitHub Gists] (gists.github.com) and link us to the file you post there.
![capture](https://user-images.githubusercontent.com/2712890/27524449-92e135f0-59fa-11e7-8f72-a167fcb93885.PNG)

**Comment by CyR1en** [comment]
@ShadowGamer225 Join our Discord server and I'll do my best to help you. I can help you here but I find it slow here.

**Comment by ViK0s** [comment]
@TheFlagCourier Ok, so here is the log https://gist.github.com/ShadowGamer225/5cc8d84faddd15430aa324053aca8524
It's very very long because i use some other plugins.
@CyR1en I joined it, my discord nickname is James Hoxworth

**Comment by TheFlagCourier** [comment]
Alright, @ShadowGamer225 - It looks like @CyR1en was right about the Polish translation file - though it's in multiple places. What bugs me is that there also seems to be an issue with authentication. 

@CyR1en  I've summarized the log file with snippets relating to Minecordbot (ignoring the repeating error after it's mention) [Summary](https://gist.github.com/TheFlagCourier/9bd13fe7fda85c3f867a87ba6eacc742)

I'll see if I can't get a YML parser to check the translation.

**Comment by TheFlagCourier** [comment]
Yup, errors in the repo when throwing the file into [this parser](https://yaml-online-parser.appspot.com)
Pushed a *hopefully fixed* file to master - at least, the local file doesn't throw an error with the parser or atom's 3rd-party yaml linter.
I'll attach the new build here.

**Comment by TheFlagCourier** [comment]
@ShadowGamer225 Here's a hot fix build. Could you test to see if the issue resolves?

[Minecordbot-2.0.6-PL_Hotfix.zip](https://github.com/CyR1en/Minecordbot-v2/files/1107249/Minecordbot-2.0.6-PL_Hotfix.zip)

**Comment by ViK0s** [comment]
Fixed!

**Comment by TheFlagCourier** [comment]
Polish translation was fixed.
We also discovered that `\` was being used as the bot trigger - resulting in a part of the bug.
(Do not use `\` - ever. It's Java's escape character.)
