### ISSUE TITLE
[Request] Export Configuration (Debug.zip)

### ISSUE THREAD

**Issue by TheFlagCourier** [CyR1en/Minecordbot#29]
Tell the bot upload an archive (.7z / .zip) of the configuration to a specified text channel, or via DM to a user, that can be used for submitting bug reports or asking for config help.

`,exportconfig`
MCB >> Packages and uploads configuration and lang files to designated mod channel, or via DM to bot owner.

----
Additionally, allow for specifying:
- `,exportconfig all` - All files in the */Plugins/Minecordbot* folder (default behavior)
- `,exportconfig cfg` - Exports only the main config file
- `,exportconfig lang` - Exports all language files
- `,exportconfig lang [lang]` - Exports specific language file.

**Comment by CyR1en** [comment]
Very clever feature

**Comment by TheFlagCourier** [comment]
Most likely unnecessary (so I hope you're using "clever" unironically.)

**Comment by TheFlagCourier** [comment]
Depreciating label 'Feature Request' for the running standard, 'Enhancement'.
