### ISSUE TITLE
'!!help' command failing to output to discord

### ISSUE THREAD

**Issue by mickael49300fr** [CyR1en/Minecordbot#34]
I have a problem the command "help" on discord it does not work, I tested with the bot in admin but its not working too.

I'm not back in the log just "MineCordBot:
mickael49300_fr executed help command. "

but nothing is displaying on discord

sorry i use google translation to write the message :-(

**Comment by TheFlagCourier** [comment]
MCB cannot handle output of the in-game `/help` command (that I know of...), nor does it output it's Discord `,help` to the game server. This would be bad practice to allow, as it would result in unnecessary spam.

However, theoretically you could do `,mcmd help` to get output from the game. This has a few more flaws in it though...
* All commands are run as console/op, so you will see all privileged in-game commands.
* Might run into different API calls to implement depending on the server version. (Looking at you, horses...)

**Comment by TheFlagCourier** [comment]
Reopening. Originally closed due to a misunderstanding. Having re-read, I see that this is related to `!!help` - a problem I am also currently experiencing.

**Comment by CyR1en** [comment]
Can't find cause of bug because there was no error log submitted that provided sufficient information. 

Although this does not persist on the previous and current version of Minecordbot.
