### ISSUE TITLE
Null Proxy Selector

### ISSUE THREAD

**Issue by nick-perry14** [CyR1en/Minecordbot#65]
31.12 17:22:56 [Server] INFO java.lang.NullPointerException: proxySelector == null

This, along with many errors given.  I am not doing anything wrong configuration end (I think)

**Comment by CyR1en** [comment]
Can you send me the error logs and a copy of all your configuration files? You can omit private informations like bot toke, owner id, etc.

**Comment by nick-perry14** [comment]
Well, it works now, without me changing any of the configs, however, I will still provide the error for you.

https://pastebin.com/UeBYHgH8

**Comment by CyR1en** [comment]
Oh okay. So is there anything else I could do for ya? :3 If not I'll close this issue

**Comment by nick-perry14** [comment]
Nope, Thanks for replying quickly.

I really am grateful.

Have an awesome week, and a happy new year!
