### ISSUE TITLE
Join/Quit messages aren't sending in Spigot 1.12.2

### ISSUE THREAD

**Issue by crashtheparty** [CyR1en/Minecordbot#96]
### What is supposed to happen?
Join/Quit messages send a message to discord.

### What actually happens?
No message is shown and throws errors in console.

### What steps reproduce the problem?
1. Install bot and plugin and add the correct bot information.
2. Refresh server.
3. Log into/out of the server.

------
### What is your Minecordbot version?
Commit 26e0ce32de32e956c873bc1b6f76b9807e8e3eed (Update **README.md**)

### What is your craftbukkit / spigot version?
Spigot 1.12.2

### Please provide a link to the following:
https://hastebin.com/muyapubogi.vbs

**Comment by crashtheparty** [comment]
I think one of my other plugins is interfering with this... but probably good to do null pointer checks in the join/quit/death listeners for the message (tested with death message as well and it broke).

**Comment by TheIntelloBox** [comment]
I have the same problem. Do you have EssentialsX?

**Comment by crashtheparty** [comment]
No I don't, but I have a custom plugin to enable/disable the join and quit messages. Modifying that plugin got me a different error ("Title cannot be blank!") so I'm assuming anything that sets joinMessage or quitMessage (or deathMessage) to null will cause this issue.

**Comment by TheIntelloBox** [comment]
Give us the full plugins list. ;)

**Comment by CyR1en** [comment]
@crashtheparty I do have a function that checks for null or empty messages
https://github.com/CyR1en/Minecordbot/blob/26e0ce32de32e956c873bc1b6f76b9807e8e3eed/src/main/java/us/cyrien/minecordbot/chat/listeners/mcListeners/UserQuitJoinListener.java#L112-L132

**Comment by crashtheparty** [comment]
Plugins currently used are this one and a custom one called DisableMessages. Code for it is as follows:

https://hastebin.com/igazudonok.java

**Comment by CyR1en** [comment]
That's probably the reason why it's not working.

**Comment by crashtheparty** [comment]
I changed the code to this to debug: https://hastebin.com/iwaluwuziy.cs

And now I'm getting this in the console: https://hastebin.com/yaruyuyuhi.vbs

**Comment by crashtheparty** [comment]
Downloaded version 2.2.2 and it works fine. Going to use that version for now.
